package org.ku8eye.domain;

import java.util.Date;

public class JenkinsOrderInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.id
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.jenkins_url
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String jenkinsUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.jenkins_username
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String jenkinsUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.API_token
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String apiToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.job_name
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String jobName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.job_status
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private Byte jobStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.build_num
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private Integer buildNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.request_type
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private Byte requestType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.LAST_UPDATED_TIME
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private Date lastUpdatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.password
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.DCOS_USER_ID
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String dcosUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.DCOS_USER_ALIAS
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String dcosUserAlias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.NOTE
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jenkins_info.order_id
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	private Integer orderId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.id
	 * @return  the value of jenkins_info.id
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.id
	 * @param id  the value for jenkins_info.id
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.jenkins_url
	 * @return  the value of jenkins_info.jenkins_url
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getJenkinsUrl() {
		return jenkinsUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.jenkins_url
	 * @param jenkinsUrl  the value for jenkins_info.jenkins_url
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setJenkinsUrl(String jenkinsUrl) {
		this.jenkinsUrl = jenkinsUrl == null ? null : jenkinsUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.jenkins_username
	 * @return  the value of jenkins_info.jenkins_username
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getJenkinsUsername() {
		return jenkinsUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.jenkins_username
	 * @param jenkinsUsername  the value for jenkins_info.jenkins_username
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setJenkinsUsername(String jenkinsUsername) {
		this.jenkinsUsername = jenkinsUsername == null ? null : jenkinsUsername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.API_token
	 * @return  the value of jenkins_info.API_token
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getApiToken() {
		return apiToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.API_token
	 * @param apiToken  the value for jenkins_info.API_token
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setApiToken(String apiToken) {
		this.apiToken = apiToken == null ? null : apiToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.job_name
	 * @return  the value of jenkins_info.job_name
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.job_name
	 * @param jobName  the value for jenkins_info.job_name
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName == null ? null : jobName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.job_status
	 * @return  the value of jenkins_info.job_status
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public Byte getJobStatus() {
		return jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.job_status
	 * @param jobStatus  the value for jenkins_info.job_status
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setJobStatus(Byte jobStatus) {
		this.jobStatus = jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.build_num
	 * @return  the value of jenkins_info.build_num
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public Integer getBuildNum() {
		return buildNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.build_num
	 * @param buildNum  the value for jenkins_info.build_num
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setBuildNum(Integer buildNum) {
		this.buildNum = buildNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.request_type
	 * @return  the value of jenkins_info.request_type
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public Byte getRequestType() {
		return requestType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.request_type
	 * @param requestType  the value for jenkins_info.request_type
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setRequestType(Byte requestType) {
		this.requestType = requestType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.LAST_UPDATED_TIME
	 * @return  the value of jenkins_info.LAST_UPDATED_TIME
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public Date getLastUpdatedTime() {
		return lastUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.LAST_UPDATED_TIME
	 * @param lastUpdatedTime  the value for jenkins_info.LAST_UPDATED_TIME
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setLastUpdatedTime(Date lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.password
	 * @return  the value of jenkins_info.password
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.password
	 * @param password  the value for jenkins_info.password
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.DCOS_USER_ID
	 * @return  the value of jenkins_info.DCOS_USER_ID
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getDcosUserId() {
		return dcosUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.DCOS_USER_ID
	 * @param dcosUserId  the value for jenkins_info.DCOS_USER_ID
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setDcosUserId(String dcosUserId) {
		this.dcosUserId = dcosUserId == null ? null : dcosUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.DCOS_USER_ALIAS
	 * @return  the value of jenkins_info.DCOS_USER_ALIAS
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getDcosUserAlias() {
		return dcosUserAlias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.DCOS_USER_ALIAS
	 * @param dcosUserAlias  the value for jenkins_info.DCOS_USER_ALIAS
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setDcosUserAlias(String dcosUserAlias) {
		this.dcosUserAlias = dcosUserAlias == null ? null : dcosUserAlias.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.NOTE
	 * @return  the value of jenkins_info.NOTE
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.NOTE
	 * @param note  the value for jenkins_info.NOTE
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jenkins_info.order_id
	 * @return  the value of jenkins_info.order_id
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jenkins_info.order_id
	 * @param orderId  the value for jenkins_info.order_id
	 * @mbg.generated  Mon Jun 26 10:43:13 CST 2017
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}
}