package org.ku8eye.domain;

import java.util.Date;

public class K8OrderBigdata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.mode
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer mode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.zone
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer zone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.version
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.cluster_count
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer clusterCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.resource_type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer resourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.storage_type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer storageType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.disk_space
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer diskSpace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.remark
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.security
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private String security;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.k8order_id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private String k8orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.user_id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.remark_admin
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private String remarkAdmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.additional_service
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer additionalService;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column k8order_bigdata.worker_number
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	private Integer workerNumber;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.id
	 * @return  the value of k8order_bigdata.id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	
    private Date startTime;	
	
	public Date getStartTime() {
		return startTime;
	}
	
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	
	public Integer getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.id
	 * @param id  the value for k8order_bigdata.id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.mode
	 * @return  the value of k8order_bigdata.mode
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getMode() {
		return mode;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.mode
	 * @param mode  the value for k8order_bigdata.mode
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setMode(Integer mode) {
		this.mode = mode;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.zone
	 * @return  the value of k8order_bigdata.zone
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getZone() {
		return zone;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.zone
	 * @param zone  the value for k8order_bigdata.zone
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setZone(Integer zone) {
		this.zone = zone;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.type
	 * @return  the value of k8order_bigdata.type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getType() {
		return type;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.type
	 * @param type  the value for k8order_bigdata.type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.version
	 * @return  the value of k8order_bigdata.version
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public String getVersion() {
		return version;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.version
	 * @param version  the value for k8order_bigdata.version
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setVersion(String version) {
		this.version = version == null ? null : version.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.cluster_count
	 * @return  the value of k8order_bigdata.cluster_count
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getClusterCount() {
		return clusterCount;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.cluster_count
	 * @param clusterCount  the value for k8order_bigdata.cluster_count
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setClusterCount(Integer clusterCount) {
		this.clusterCount = clusterCount;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.resource_type
	 * @return  the value of k8order_bigdata.resource_type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getResourceType() {
		return resourceType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.resource_type
	 * @param resourceType  the value for k8order_bigdata.resource_type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setResourceType(Integer resourceType) {
		this.resourceType = resourceType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.storage_type
	 * @return  the value of k8order_bigdata.storage_type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getStorageType() {
		return storageType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.storage_type
	 * @param storageType  the value for k8order_bigdata.storage_type
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setStorageType(Integer storageType) {
		this.storageType = storageType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.disk_space
	 * @return  the value of k8order_bigdata.disk_space
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getDiskSpace() {
		return diskSpace;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.disk_space
	 * @param diskSpace  the value for k8order_bigdata.disk_space
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setDiskSpace(Integer diskSpace) {
		this.diskSpace = diskSpace;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.remark
	 * @return  the value of k8order_bigdata.remark
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public String getRemark() {
		return remark;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.remark
	 * @param remark  the value for k8order_bigdata.remark
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.security
	 * @return  the value of k8order_bigdata.security
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public String getSecurity() {
		return security;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.security
	 * @param security  the value for k8order_bigdata.security
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setSecurity(String security) {
		this.security = security == null ? null : security.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.k8order_id
	 * @return  the value of k8order_bigdata.k8order_id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public String getK8orderId() {
		return k8orderId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.k8order_id
	 * @param k8orderId  the value for k8order_bigdata.k8order_id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setK8orderId(String k8orderId) {
		this.k8orderId = k8orderId == null ? null : k8orderId.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.user_id
	 * @return  the value of k8order_bigdata.user_id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public String getUserId() {
		return userId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.user_id
	 * @param userId  the value for k8order_bigdata.user_id
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.remark_admin
	 * @return  the value of k8order_bigdata.remark_admin
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public String getRemarkAdmin() {
		return remarkAdmin;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.remark_admin
	 * @param remarkAdmin  the value for k8order_bigdata.remark_admin
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setRemarkAdmin(String remarkAdmin) {
		this.remarkAdmin = remarkAdmin == null ? null : remarkAdmin.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.additional_service
	 * @return  the value of k8order_bigdata.additional_service
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getAdditionalService() {
		return additionalService;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.additional_service
	 * @param additionalService  the value for k8order_bigdata.additional_service
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setAdditionalService(Integer additionalService) {
		this.additionalService = additionalService;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column k8order_bigdata.worker_number
	 * @return  the value of k8order_bigdata.worker_number
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public Integer getWorkerNumber() {
		return workerNumber;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column k8order_bigdata.worker_number
	 * @param workerNumber  the value for k8order_bigdata.worker_number
	 * @mbg.generated  Wed Aug 30 10:47:01 CST 2017
	 */
	public void setWorkerNumber(Integer workerNumber) {
		this.workerNumber = workerNumber;
	}
	private Integer status;
    public Integer getStatus() {
        return status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
}