package org.ku8eye.domain;

import java.util.Date;

public class K8OrderDatabase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer id;
    private Integer status;
    
    private Date startTime;
    
    public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.status
     *
     * @param status the value for k8order.status
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.zone
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.version
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.cluster_count
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer clusterCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.resource_type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.storage_type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer storageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.disk_space
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer diskSpace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.database_name
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String databaseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.username
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.password
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.url
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.port
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.remark
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.security
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String security;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.additional_service
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private Integer additionalService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.k8order_id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String k8orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.user_id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order_database.remark_admin
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    private String remarkAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.id
     *
     * @return the value of k8order_database.id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.id
     *
     * @param id the value for k8order_database.id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.zone
     *
     * @return the value of k8order_database.zone
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.zone
     *
     * @param zone the value for k8order_database.zone
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setZone(Integer zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.type
     *
     * @return the value of k8order_database.type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.type
     *
     * @param type the value for k8order_database.type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.version
     *
     * @return the value of k8order_database.version
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.version
     *
     * @param version the value for k8order_database.version
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.cluster_count
     *
     * @return the value of k8order_database.cluster_count
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getClusterCount() {
        return clusterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.cluster_count
     *
     * @param clusterCount the value for k8order_database.cluster_count
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setClusterCount(Integer clusterCount) {
        this.clusterCount = clusterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.resource_type
     *
     * @return the value of k8order_database.resource_type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.resource_type
     *
     * @param resourceType the value for k8order_database.resource_type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.storage_type
     *
     * @return the value of k8order_database.storage_type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.storage_type
     *
     * @param storageType the value for k8order_database.storage_type
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setStorageType(Integer storageType) {
        this.storageType = storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.disk_space
     *
     * @return the value of k8order_database.disk_space
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getDiskSpace() {
        return diskSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.disk_space
     *
     * @param diskSpace the value for k8order_database.disk_space
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setDiskSpace(Integer diskSpace) {
        this.diskSpace = diskSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.database_name
     *
     * @return the value of k8order_database.database_name
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.database_name
     *
     * @param databaseName the value for k8order_database.database_name
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName == null ? null : databaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.username
     *
     * @return the value of k8order_database.username
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.username
     *
     * @param username the value for k8order_database.username
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.password
     *
     * @return the value of k8order_database.password
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.password
     *
     * @param password the value for k8order_database.password
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.url
     *
     * @return the value of k8order_database.url
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.url
     *
     * @param url the value for k8order_database.url
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.port
     *
     * @return the value of k8order_database.port
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.port
     *
     * @param port the value for k8order_database.port
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.remark
     *
     * @return the value of k8order_database.remark
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.remark
     *
     * @param remark the value for k8order_database.remark
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.security
     *
     * @return the value of k8order_database.security
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getSecurity() {
        return security;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.security
     *
     * @param security the value for k8order_database.security
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setSecurity(String security) {
        this.security = security == null ? null : security.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.additional_service
     *
     * @return the value of k8order_database.additional_service
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public Integer getAdditionalService() {
        return additionalService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.additional_service
     *
     * @param additionalService the value for k8order_database.additional_service
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setAdditionalService(Integer additionalService) {
        this.additionalService = additionalService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.k8order_id
     *
     * @return the value of k8order_database.k8order_id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getK8orderId() {
        return k8orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.k8order_id
     *
     * @param k8orderId the value for k8order_database.k8order_id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setK8orderId(String k8orderId) {
        this.k8orderId = k8orderId == null ? null : k8orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.user_id
     *
     * @return the value of k8order_database.user_id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.user_id
     *
     * @param userId the value for k8order_database.user_id
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order_database.remark_admin
     *
     * @return the value of k8order_database.remark_admin
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public String getRemarkAdmin() {
        return remarkAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order_database.remark_admin
     *
     * @param remarkAdmin the value for k8order_database.remark_admin
     *
     * @mbg.generated Wed Jul 26 16:40:45 CST 2017
     */
    public void setRemarkAdmin(String remarkAdmin) {
        this.remarkAdmin = remarkAdmin == null ? null : remarkAdmin.trim();
    }
}