package org.ku8eye.domain;

import java.util.Date;

public class K8Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.k8order_id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private String k8orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.create_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.k8order_type
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private String k8orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.status
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.user_id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.start_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column k8order.end_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.id
     *
     * @return the value of k8order.id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.id
     *
     * @param id the value for k8order.id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.k8order_id
     *
     * @return the value of k8order.k8order_id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public String getK8orderId() {
        return k8orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.k8order_id
     *
     * @param k8orderId the value for k8order.k8order_id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setK8orderId(String k8orderId) {
        this.k8orderId = k8orderId == null ? null : k8orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.create_time
     *
     * @return the value of k8order.create_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.create_time
     *
     * @param createTime the value for k8order.create_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.k8order_type
     *
     * @return the value of k8order.k8order_type
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public String getK8orderType() {
        return k8orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.k8order_type
     *
     * @param k8orderType the value for k8order.k8order_type
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setK8orderType(String k8orderType) {
        this.k8orderType = k8orderType == null ? null : k8orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.status
     *
     * @return the value of k8order.status
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.status
     *
     * @param status the value for k8order.status
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.user_id
     *
     * @return the value of k8order.user_id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.user_id
     *
     * @param userId the value for k8order.user_id
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.start_time
     *
     * @return the value of k8order.start_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.start_time
     *
     * @param startTime the value for k8order.start_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column k8order.end_time
     *
     * @return the value of k8order.end_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column k8order.end_time
     *
     * @param endTime the value for k8order.end_time
     *
     * @mbg.generated Mon Jul 31 15:25:22 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}