package org.ku8eye.domain;

public class Ku8ConfigMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_config_map.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_config_map.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_config_map.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_config_map.CLUSTER_NAME
     *
     * @mbggenerated
     */
    private String clusterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_config_map.NAMESPACE
     *
     * @mbggenerated
     */
    private String namespace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_config_map.ID
     *
     * @return the value of ku8_config_map.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_config_map.ID
     *
     * @param id the value for ku8_config_map.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_config_map.NAME
     *
     * @return the value of ku8_config_map.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_config_map.NAME
     *
     * @param name the value for ku8_config_map.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_config_map.CLUSTER_ID
     *
     * @return the value of ku8_config_map.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_config_map.CLUSTER_ID
     *
     * @param clusterId the value for ku8_config_map.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_config_map.NAMESPACE
     *
     * @return the value of ku8_config_map.NAMESPACE
     *
     * @mbggenerated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_config_map.NAMESPACE
     *
     * @param namespace the value for ku8_config_map.NAMESPACE
     *
     * @mbggenerated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

	public String getClusterName()
	{
		return clusterName;
	}

	public void setClusterName(String clusterName)
	{
		this.clusterName = clusterName;
	}
}