package org.ku8eye.domain;

import java.util.Date;

import org.ku8eye.bean.task.TaskInfo;

public class Ku8Job {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.TENANT_ID
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.OWNER
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.ICON_URL
     *
     * @mbggenerated
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.RES_PART
     *
     * @mbggenerated
     */
    private String resPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.ZONE_ID
     *
     * @mbggenerated
     */
    private Integer zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.CLUSTER_ID
     *
     * @mbggenerated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.RES_PARTION_ID
     *
     * @mbggenerated
     */
    private Integer resPartionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.STATUS
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.PROGRESS
     *
     * @mbggenerated
     */
    private Integer progress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.JOB_TYPE
     *
     * @mbggenerated
     */
    private Integer jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.TASK_STATUS
     *
     * @mbggenerated
     */
    private Byte taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.JSON_SPEC
     *
     * @mbggenerated
     */
    private String jsonSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku8_job.PREV_JSON_SPEC
     *
     * @mbggenerated
     */
    private String prevJsonSpec;
    
    private TaskInfo taskInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.ID
     *
     * @return the value of ku8_job.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.ID
     *
     * @param id the value for ku8_job.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.TENANT_ID
     *
     * @return the value of ku8_job.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.TENANT_ID
     *
     * @param tenantId the value for ku8_job.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.OWNER
     *
     * @return the value of ku8_job.OWNER
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.OWNER
     *
     * @param owner the value for ku8_job.OWNER
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.NAME
     *
     * @return the value of ku8_job.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.NAME
     *
     * @param name the value for ku8_job.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.ICON_URL
     *
     * @return the value of ku8_job.ICON_URL
     *
     * @mbggenerated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.ICON_URL
     *
     * @param iconUrl the value for ku8_job.ICON_URL
     *
     * @mbggenerated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.VERSION
     *
     * @return the value of ku8_job.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.VERSION
     *
     * @param version the value for ku8_job.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.RES_PART
     *
     * @return the value of ku8_job.RES_PART
     *
     * @mbggenerated
     */
    public String getResPart() {
        return resPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.RES_PART
     *
     * @param resPart the value for ku8_job.RES_PART
     *
     * @mbggenerated
     */
    public void setResPart(String resPart) {
        this.resPart = resPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.ZONE_ID
     *
     * @return the value of ku8_job.ZONE_ID
     *
     * @mbggenerated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.ZONE_ID
     *
     * @param zoneId the value for ku8_job.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.CLUSTER_ID
     *
     * @return the value of ku8_job.CLUSTER_ID
     *
     * @mbggenerated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.CLUSTER_ID
     *
     * @param clusterId the value for ku8_job.CLUSTER_ID
     *
     * @mbggenerated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.RES_PARTION_ID
     *
     * @return the value of ku8_job.RES_PARTION_ID
     *
     * @mbggenerated
     */
    public Integer getResPartionId() {
        return resPartionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.RES_PARTION_ID
     *
     * @param resPartionId the value for ku8_job.RES_PARTION_ID
     *
     * @mbggenerated
     */
    public void setResPartionId(Integer resPartionId) {
        this.resPartionId = resPartionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.STATUS
     *
     * @return the value of ku8_job.STATUS
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.STATUS
     *
     * @param status the value for ku8_job.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.PROGRESS
     *
     * @return the value of ku8_job.PROGRESS
     *
     * @mbggenerated
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.PROGRESS
     *
     * @param progress the value for ku8_job.PROGRESS
     *
     * @mbggenerated
     */
    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.NOTE
     *
     * @return the value of ku8_job.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.NOTE
     *
     * @param note the value for ku8_job.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.JOB_TYPE
     *
     * @return the value of ku8_job.JOB_TYPE
     *
     * @mbggenerated
     */
    public Integer getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.JOB_TYPE
     *
     * @param jobType the value for ku8_job.JOB_TYPE
     *
     * @mbggenerated
     */
    public void setJobType(Integer jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.TASK_STATUS
     *
     * @return the value of ku8_job.TASK_STATUS
     *
     * @mbggenerated
     */
    public Byte getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.TASK_STATUS
     *
     * @param taskStatus the value for ku8_job.TASK_STATUS
     *
     * @mbggenerated
     */
    public void setTaskStatus(Byte taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.CRON_EXPRESSION
     *
     * @return the value of ku8_job.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.CRON_EXPRESSION
     *
     * @param cronExpression the value for ku8_job.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.LAST_UPDATED
     *
     * @return the value of ku8_job.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.LAST_UPDATED
     *
     * @param lastUpdated the value for ku8_job.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.JSON_SPEC
     *
     * @return the value of ku8_job.JSON_SPEC
     *
     * @mbggenerated
     */
    public String getJsonSpec() {
        return jsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.JSON_SPEC
     *
     * @param jsonSpec the value for ku8_job.JSON_SPEC
     *
     * @mbggenerated
     */
    public void setJsonSpec(String jsonSpec) {
        this.jsonSpec = jsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku8_job.PREV_JSON_SPEC
     *
     * @return the value of ku8_job.PREV_JSON_SPEC
     *
     * @mbggenerated
     */
    public String getPrevJsonSpec() {
        return prevJsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku8_job.PREV_JSON_SPEC
     *
     * @param prevJsonSpec the value for ku8_job.PREV_JSON_SPEC
     *
     * @mbggenerated
     */
    public void setPrevJsonSpec(String prevJsonSpec) {
        this.prevJsonSpec = prevJsonSpec;
    }

	public TaskInfo getTaskInfo()
	{
		return taskInfo;
	}

	public void setTaskInfo(TaskInfo taskInfo)
	{
		this.taskInfo = taskInfo;
	}
}