package org.ku8eye.domain;

import java.util.Date;

public class UserAbilityInstance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.user_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.ability_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private String abilityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.ability_name
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private String abilityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.ability_type
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private Integer abilityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.deliver_describe
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private String deliverDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.order_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.ability_instance
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private String abilityInstance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.create_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.start_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.end_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ability_instance.zone_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    private Integer zoneId;
    
    
    private String createUrl;
    
    
    private String abilityDesc;
    
    
    private Integer abilityStatus;

	public Integer getAbilityStatus() {
		return abilityStatus;
	}

	public void setAbilityStatus(Integer abilityStatus) {
		this.abilityStatus = abilityStatus;
	}

	public String getAbilityDesc() {
		return abilityDesc;
	}

	public void setAbilityDesc(String abilityDesc) {
		this.abilityDesc = abilityDesc;
	}

	public String getCreateUrl() {
		return createUrl;
	}

	public void setCreateUrl(String createUrl) {
		this.createUrl = createUrl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.id
     *
     * @return the value of user_ability_instance.id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.id
     *
     * @param id the value for user_ability_instance.id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.user_id
     *
     * @return the value of user_ability_instance.user_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.user_id
     *
     * @param userId the value for user_ability_instance.user_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.ability_id
     *
     * @return the value of user_ability_instance.ability_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public String getAbilityId() {
        return abilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.ability_id
     *
     * @param abilityId the value for user_ability_instance.ability_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setAbilityId(String abilityId) {
        this.abilityId = abilityId == null ? null : abilityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.ability_name
     *
     * @return the value of user_ability_instance.ability_name
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public String getAbilityName() {
        return abilityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.ability_name
     *
     * @param abilityName the value for user_ability_instance.ability_name
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setAbilityName(String abilityName) {
        this.abilityName = abilityName == null ? null : abilityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.ability_type
     *
     * @return the value of user_ability_instance.ability_type
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public Integer getAbilityType() {
        return abilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.ability_type
     *
     * @param abilityType the value for user_ability_instance.ability_type
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setAbilityType(Integer abilityType) {
        this.abilityType = abilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.deliver_describe
     *
     * @return the value of user_ability_instance.deliver_describe
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public String getDeliverDescribe() {
        return deliverDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.deliver_describe
     *
     * @param deliverDescribe the value for user_ability_instance.deliver_describe
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setDeliverDescribe(String deliverDescribe) {
        this.deliverDescribe = deliverDescribe == null ? null : deliverDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.order_id
     *
     * @return the value of user_ability_instance.order_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.order_id
     *
     * @param orderId the value for user_ability_instance.order_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.ability_instance
     *
     * @return the value of user_ability_instance.ability_instance
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public String getAbilityInstance() {
        return abilityInstance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.ability_instance
     *
     * @param abilityInstance the value for user_ability_instance.ability_instance
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setAbilityInstance(String abilityInstance) {
        this.abilityInstance = abilityInstance == null ? null : abilityInstance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.create_time
     *
     * @return the value of user_ability_instance.create_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.create_time
     *
     * @param createTime the value for user_ability_instance.create_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.start_time
     *
     * @return the value of user_ability_instance.start_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.start_time
     *
     * @param startTime the value for user_ability_instance.start_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.end_time
     *
     * @return the value of user_ability_instance.end_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.end_time
     *
     * @param endTime the value for user_ability_instance.end_time
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ability_instance.zone_id
     *
     * @return the value of user_ability_instance.zone_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ability_instance.zone_id
     *
     * @param zoneId the value for user_ability_instance.zone_id
     *
     * @mbg.generated Tue Nov 29 18:35:23 CST 2016
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }
}