package org.ku8eye.domain;

import java.util.Date;

public class UserOrderCopy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.order_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.order_no
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.tenant_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.user_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.status
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.create_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.update_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.remark
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.start_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.end_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.zone_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Integer zoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_copy.order_type
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    private Integer orderType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.order_id
     *
     * @return the value of user_order_copy.order_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.order_id
     *
     * @param orderId the value for user_order_copy.order_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.order_no
     *
     * @return the value of user_order_copy.order_no
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.order_no
     *
     * @param orderNo the value for user_order_copy.order_no
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.tenant_id
     *
     * @return the value of user_order_copy.tenant_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.tenant_id
     *
     * @param tenantId the value for user_order_copy.tenant_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.user_id
     *
     * @return the value of user_order_copy.user_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.user_id
     *
     * @param userId the value for user_order_copy.user_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.status
     *
     * @return the value of user_order_copy.status
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.status
     *
     * @param status the value for user_order_copy.status
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.create_time
     *
     * @return the value of user_order_copy.create_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.create_time
     *
     * @param createTime the value for user_order_copy.create_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.update_time
     *
     * @return the value of user_order_copy.update_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.update_time
     *
     * @param updateTime the value for user_order_copy.update_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.remark
     *
     * @return the value of user_order_copy.remark
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.remark
     *
     * @param remark the value for user_order_copy.remark
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.start_time
     *
     * @return the value of user_order_copy.start_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.start_time
     *
     * @param startTime the value for user_order_copy.start_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.end_time
     *
     * @return the value of user_order_copy.end_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.end_time
     *
     * @param endTime the value for user_order_copy.end_time
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.zone_id
     *
     * @return the value of user_order_copy.zone_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.zone_id
     *
     * @param zoneId the value for user_order_copy.zone_id
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_copy.order_type
     *
     * @return the value of user_order_copy.order_type
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_copy.order_type
     *
     * @param orderType the value for user_order_copy.order_type
     *
     * @mbg.generated Tue Jun 06 15:42:36 CST 2017
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }
}