package org.ku8eye.domain;

import java.util.Date;

public class UserAbilityInstanceDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.user_ability_instance_id
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private Integer userAbilityInstanceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.user_id
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.repo_name
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private String repoName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.deliver_describe
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private String deliverDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.ability_instance
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private String abilityInstance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.resource_type
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private Integer resourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.username
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.password
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_ability_instance_detail.ability_instance_url
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	private String abilityInstanceUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.user_ability_instance_id
	 * @return  the value of user_ability_instance_detail.user_ability_instance_id
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public Integer getUserAbilityInstanceId() {
		return userAbilityInstanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.user_ability_instance_id
	 * @param userAbilityInstanceId  the value for user_ability_instance_detail.user_ability_instance_id
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setUserAbilityInstanceId(Integer userAbilityInstanceId) {
		this.userAbilityInstanceId = userAbilityInstanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.user_id
	 * @return  the value of user_ability_instance_detail.user_id
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.user_id
	 * @param userId  the value for user_ability_instance_detail.user_id
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.repo_name
	 * @return  the value of user_ability_instance_detail.repo_name
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public String getRepoName() {
		return repoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.repo_name
	 * @param repoName  the value for user_ability_instance_detail.repo_name
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setRepoName(String repoName) {
		this.repoName = repoName == null ? null : repoName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.deliver_describe
	 * @return  the value of user_ability_instance_detail.deliver_describe
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public String getDeliverDescribe() {
		return deliverDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.deliver_describe
	 * @param deliverDescribe  the value for user_ability_instance_detail.deliver_describe
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setDeliverDescribe(String deliverDescribe) {
		this.deliverDescribe = deliverDescribe == null ? null : deliverDescribe.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.ability_instance
	 * @return  the value of user_ability_instance_detail.ability_instance
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public String getAbilityInstance() {
		return abilityInstance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.ability_instance
	 * @param abilityInstance  the value for user_ability_instance_detail.ability_instance
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setAbilityInstance(String abilityInstance) {
		this.abilityInstance = abilityInstance == null ? null : abilityInstance.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.resource_type
	 * @return  the value of user_ability_instance_detail.resource_type
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public Integer getResourceType() {
		return resourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.resource_type
	 * @param resourceType  the value for user_ability_instance_detail.resource_type
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setResourceType(Integer resourceType) {
		this.resourceType = resourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.username
	 * @return  the value of user_ability_instance_detail.username
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.username
	 * @param username  the value for user_ability_instance_detail.username
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.password
	 * @return  the value of user_ability_instance_detail.password
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.password
	 * @param password  the value for user_ability_instance_detail.password
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_ability_instance_detail.ability_instance_url
	 * @return  the value of user_ability_instance_detail.ability_instance_url
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public String getAbilityInstanceUrl() {
		return abilityInstanceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_ability_instance_detail.ability_instance_url
	 * @param abilityInstanceUrl  the value for user_ability_instance_detail.ability_instance_url
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	public void setAbilityInstanceUrl(String abilityInstanceUrl) {
		this.abilityInstanceUrl = abilityInstanceUrl == null ? null : abilityInstanceUrl.trim();
	}
}