package org.ku8eye.domain;

import java.util.Date;

public class WarRegistry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column war_registry.id
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column war_registry.title
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column war_registry.date
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column war_registry.user
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column war_registry.extension
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column war_registry.mark
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column war_registry.location
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column war_registry.id
     *
     * @return the value of war_registry.id
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column war_registry.id
     *
     * @param id the value for war_registry.id
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column war_registry.title
     *
     * @return the value of war_registry.title
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column war_registry.title
     *
     * @param title the value for war_registry.title
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column war_registry.date
     *
     * @return the value of war_registry.date
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column war_registry.date
     *
     * @param date the value for war_registry.date
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column war_registry.user
     *
     * @return the value of war_registry.user
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column war_registry.user
     *
     * @param user the value for war_registry.user
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column war_registry.extension
     *
     * @return the value of war_registry.extension
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column war_registry.extension
     *
     * @param extension the value for war_registry.extension
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column war_registry.mark
     *
     * @return the value of war_registry.mark
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column war_registry.mark
     *
     * @param mark the value for war_registry.mark
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column war_registry.location
     *
     * @return the value of war_registry.location
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column war_registry.location
     *
     * @param location the value for war_registry.location
     *
     * @mbg.generated Wed Jun 28 15:45:40 CST 2017
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}