package org.ku8eye.domain;

import java.util.Date;

public class YamlRegistry {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yaml_registry.ID
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	private Byte id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yaml_registry.title
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yaml_registry.date
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yaml_registry.author
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yaml_registry.extension
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	private String extension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yaml_registry.content
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yaml_registry.ID
	 * @return  the value of yaml_registry.ID
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public Byte getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yaml_registry.ID
	 * @param id  the value for yaml_registry.ID
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public void setId(Byte id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yaml_registry.title
	 * @return  the value of yaml_registry.title
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yaml_registry.title
	 * @param title  the value for yaml_registry.title
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yaml_registry.date
	 * @return  the value of yaml_registry.date
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yaml_registry.date
	 * @param date  the value for yaml_registry.date
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yaml_registry.author
	 * @return  the value of yaml_registry.author
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yaml_registry.author
	 * @param author  the value for yaml_registry.author
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yaml_registry.extension
	 * @return  the value of yaml_registry.extension
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public String getExtension() {
		return extension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yaml_registry.extension
	 * @param extension  the value for yaml_registry.extension
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public void setExtension(String extension) {
		this.extension = extension == null ? null : extension.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yaml_registry.content
	 * @return  the value of yaml_registry.content
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yaml_registry.content
	 * @param content  the value for yaml_registry.content
	 * @mbg.generated  Sun Apr 16 23:57:52 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}