package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8ConfigMap;

public interface Ku8ConfigMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_config_map
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_config_map",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);
    
	@Delete({ "delete from ku8_config_map", "where CLUSTER_ID = #{id,jdbcType=INTEGER}" })
	int deleteByClusterId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_config_map
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_config_map (ID, NAME, ",
        "CLUSTER_ID, NAMESPACE)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{clusterId,jdbcType=INTEGER}, #{namespace,jdbcType=CHAR})"
    })
    int insert(Ku8ConfigMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_config_map
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, NAME, CLUSTER_ID, NAMESPACE",
        "from ku8_config_map",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR)
    })
    Ku8ConfigMap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_config_map
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, NAME, CLUSTER_ID, NAMESPACE",
        "from ku8_config_map"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="NAMESPACE", property="namespace", jdbcType=JdbcType.CHAR)
    })
    List<Ku8ConfigMap> selectAll();
    
	/**
	 * select By cluster Id
	 * 
	 * @param id
	 * @return
	 */
	@Select({ "select ID, CLUSTER_ID, NAME, NAMESPACE from ku8_config_map","where CLUSTER_ID = #{id,jdbcType=INTEGER}"})
	@Results({
			@Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "CLUSTER_ID", property = "clusterId", jdbcType = JdbcType.INTEGER),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "NAMESPACE", property = "namespace", jdbcType = JdbcType.VARCHAR)
	})
	List<Ku8ConfigMap> selectClusterId(Integer id);
	
	/**
	 * 
	 * @author zy
	 * @version 2016年3月29日  下午3:38:30
	 * @param tenandId
	 * @return
	 */
    @Select({
        "select",
        "a.ID, a.CLUSTER_ID, b.NAME as CLUSTER_NAME, a.NAME, a.NAMESPACE",
        "from ku8_config_map a left join ku8_cluster b on a.cluster_id=b.id",
        "where cluster_id in(select id from ku8_cluster where tenant_id=#{tenandId,jdbcType=INTEGER})"
    })
    @Results({
    	@Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER, id = true),
		@Result(column = "CLUSTER_ID", property = "clusterId", jdbcType = JdbcType.INTEGER),
		@Result(column = "CLUSTER_NAME", property = "clusterName", jdbcType = JdbcType.VARCHAR),
		@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
		@Result(column = "NAMESPACE", property = "namespace", jdbcType = JdbcType.VARCHAR)
    })
    List<Ku8ConfigMap> selectByTenantId(Integer tenandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_config_map
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_config_map",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "CLUSTER_ID = #{clusterId,jdbcType=INTEGER},",
          "NAMESPACE = #{namespace,jdbcType=CHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8ConfigMap record);
}