package org.ku8eye.mapping;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.Ku8Project;

public interface Ku8ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ku8_project",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ku8_project (ID, TENANT_ID, ",
        "OWNER, NAME, ICON_URL, ",
        "VERSION, RES_PART, ",
        "APP_TYPE, ZONE_ID, ",
        "CLUSTER_ID, RES_PARTION_ID, ",
        "STATUS, PROGRESS, ",
        "NOTE, JSON_SPEC, PREV_JSON_SPEC)",
        "values (#{id,jdbcType=INTEGER}, #{tenantId,jdbcType=INTEGER}, ",
        "#{owner,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, #{iconUrl,jdbcType=VARCHAR}, ",
        "#{version,jdbcType=CHAR}, #{resPart,jdbcType=VARCHAR}, ",
        "#{appType,jdbcType=TINYINT}, #{zoneId,jdbcType=INTEGER}, ",
        "#{clusterId,jdbcType=INTEGER}, #{resPartionId,jdbcType=INTEGER}, ",
        "#{status,jdbcType=TINYINT}, #{progress,jdbcType=INTEGER}, ",
        "#{note,jdbcType=VARCHAR}, #{jsonSpec,jdbcType=LONGVARCHAR}, #{prevJsonSpec,jdbcType=LONGVARCHAR})"
    })
    int insert(Ku8Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME, ICON_URL, VERSION, RES_PART, APP_TYPE, ",
        "ZONE_ID, CLUSTER_ID, RES_PARTION_ID, STATUS, PROGRESS, NOTE, LAST_UPDATED, JSON_SPEC, ",
        "PREV_JSON_SPEC",
        "from ku8_project",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICON_URL", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.CHAR),
        @Result(column="RES_PART", property="resPart", jdbcType=JdbcType.VARCHAR),
        @Result(column="APP_TYPE", property="appType", jdbcType=JdbcType.TINYINT),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="RES_PARTION_ID", property="resPartionId", jdbcType=JdbcType.INTEGER),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="PROGRESS", property="progress", jdbcType=JdbcType.INTEGER),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="JSON_SPEC", property="jsonSpec", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="PREV_JSON_SPEC", property="prevJsonSpec", jdbcType=JdbcType.LONGVARCHAR)
    })
    Ku8Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME, ICON_URL, VERSION, RES_PART, APP_TYPE, ",
        "ZONE_ID, CLUSTER_ID, RES_PARTION_ID, STATUS, PROGRESS, NOTE, LAST_UPDATED, JSON_SPEC, ",
        "PREV_JSON_SPEC",
        "from ku8_project"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICON_URL", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.CHAR),
        @Result(column="RES_PART", property="resPart", jdbcType=JdbcType.VARCHAR),
        @Result(column="APP_TYPE", property="appType", jdbcType=JdbcType.TINYINT),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="RES_PARTION_ID", property="resPartionId", jdbcType=JdbcType.INTEGER),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="PROGRESS", property="progress", jdbcType=JdbcType.INTEGER),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="JSON_SPEC", property="jsonSpec", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="PREV_JSON_SPEC", property="prevJsonSpec", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Ku8Project> selectAll();
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME, ICON_URL, VERSION, RES_PART, APP_TYPE, ",
        "ZONE_ID, CLUSTER_ID, RES_PARTION_ID, STATUS, PROGRESS, NOTE, LAST_UPDATED, JSON_SPEC, ",
        "PREV_JSON_SPEC",
        "from ku8_project where ZONE_ID = #{zoneid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICON_URL", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.CHAR),
        @Result(column="RES_PART", property="resPart", jdbcType=JdbcType.VARCHAR),
        @Result(column="APP_TYPE", property="appType", jdbcType=JdbcType.TINYINT),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="RES_PARTION_ID", property="resPartionId", jdbcType=JdbcType.INTEGER),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="PROGRESS", property="progress", jdbcType=JdbcType.INTEGER),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="JSON_SPEC", property="jsonSpec", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="PREV_JSON_SPEC", property="prevJsonSpec", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Ku8Project> selectAllZoneId(int zoneid);

    
    @Select({
        "select",
        "ID, TENANT_ID, OWNER, NAME, ICON_URL, VERSION, RES_PART, APP_TYPE, ",
        "ZONE_ID, CLUSTER_ID, RES_PARTION_ID, STATUS, PROGRESS, NOTE, LAST_UPDATED, JSON_SPEC, ",
        "PREV_JSON_SPEC",
        "from ku8_project where OWNER = #{owner,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="OWNER", property="owner", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICON_URL", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.CHAR),
        @Result(column="RES_PART", property="resPart", jdbcType=JdbcType.VARCHAR),
        @Result(column="APP_TYPE", property="appType", jdbcType=JdbcType.TINYINT),
        @Result(column="ZONE_ID", property="zoneId", jdbcType=JdbcType.INTEGER),
        @Result(column="CLUSTER_ID", property="clusterId", jdbcType=JdbcType.INTEGER),
        @Result(column="RES_PARTION_ID", property="resPartionId", jdbcType=JdbcType.INTEGER),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="PROGRESS", property="progress", jdbcType=JdbcType.INTEGER),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="JSON_SPEC", property="jsonSpec", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="PREV_JSON_SPEC", property="prevJsonSpec", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Ku8Project> selectByOwner(String owner);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku8_project
     *
     * @mbggenerated
     */
    @Update({
        "update ku8_project",
        "set TENANT_ID = #{tenantId,jdbcType=INTEGER},",
          "OWNER = #{owner,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "ICON_URL = #{iconUrl,jdbcType=VARCHAR},",
          "VERSION = #{version,jdbcType=CHAR},",
          "RES_PART = #{resPart,jdbcType=VARCHAR},",
          "APP_TYPE = #{appType,jdbcType=TINYINT},",
          "ZONE_ID = #{zoneId,jdbcType=INTEGER},",
          "CLUSTER_ID = #{clusterId,jdbcType=INTEGER},",
          "RES_PARTION_ID = #{resPartionId,jdbcType=INTEGER},",
          "STATUS = #{status,jdbcType=TINYINT},",
          "PROGRESS = #{progress,jdbcType=INTEGER},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "JSON_SPEC = #{jsonSpec,jdbcType=LONGVARCHAR},",
          "PREV_JSON_SPEC = #{prevJsonSpec,jdbcType=LONGVARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ku8Project record);
    
    @Update({
        "update ku8_project",
        "set JSON_SPEC = #{jsonSpec,jdbcType=LONGVARCHAR},",
          "PREV_JSON_SPEC = #{prevJsonSpec,jdbcType=LONGVARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateJSON(@Param("id")Integer id, @Param("jsonSpec")String jsonSpec, @Param("prevJsonSpec")String prevJsonSpec);
}