package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.UserAbilityInstanceDetail;

public interface UserAbilityInstanceDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_ability_instance_detail
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	@Delete({ "delete from user_ability_instance_detail",
			"where user_ability_instance_id = #{userAbilityInstanceId,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer userAbilityInstanceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_ability_instance_detail
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	@Insert({ "insert into user_ability_instance_detail (user_ability_instance_id, user_id, ",
			"repo_name, deliver_describe, ", "ability_instance, resource_type, ", "username, password, ",
			"ability_instance_url)", "values (#{userAbilityInstanceId,jdbcType=INTEGER}, #{userId,jdbcType=VARCHAR}, ",
			"#{repoName,jdbcType=VARCHAR}, #{deliverDescribe,jdbcType=VARCHAR}, ",
			"#{abilityInstance,jdbcType=VARCHAR}, #{resourceType,jdbcType=INTEGER}, ",
			"#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ", "#{abilityInstanceUrl,jdbcType=VARCHAR})" })
	int insert(UserAbilityInstanceDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_ability_instance_detail
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	@Select({ "select", "user_ability_instance_id, user_id, repo_name, deliver_describe, ability_instance, ",
			"resource_type, username, password, ability_instance_url", "from user_ability_instance_detail",
			"where user_ability_instance_id = #{userAbilityInstanceId,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "user_ability_instance_id", property = "userAbilityInstanceId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "repo_name", property = "repoName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "deliver_describe", property = "deliverDescribe", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ability_instance", property = "abilityInstance", jdbcType = JdbcType.VARCHAR),
			@Result(column = "resource_type", property = "resourceType", jdbcType = JdbcType.INTEGER),
			@Result(column = "username", property = "username", jdbcType = JdbcType.VARCHAR),
			@Result(column = "password", property = "password", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ability_instance_url", property = "abilityInstanceUrl", jdbcType = JdbcType.VARCHAR) })
	UserAbilityInstanceDetail selectByPrimaryKey(Integer userAbilityInstanceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_ability_instance_detail
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	@Select({ "select", "user_ability_instance_id, user_id, repo_name, deliver_describe, ability_instance, ",
			"resource_type, username, password, ability_instance_url", "from user_ability_instance_detail" })
	@Results({
			@Result(column = "user_ability_instance_id", property = "userAbilityInstanceId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "repo_name", property = "repoName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "deliver_describe", property = "deliverDescribe", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ability_instance", property = "abilityInstance", jdbcType = JdbcType.VARCHAR),
			@Result(column = "resource_type", property = "resourceType", jdbcType = JdbcType.INTEGER),
			@Result(column = "username", property = "username", jdbcType = JdbcType.VARCHAR),
			@Result(column = "password", property = "password", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ability_instance_url", property = "abilityInstanceUrl", jdbcType = JdbcType.VARCHAR) })
	List<UserAbilityInstanceDetail> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_ability_instance_detail
	 * @mbg.generated  Thu Jul 06 15:52:11 CST 2017
	 */
	@Update({ "update user_ability_instance_detail", "set user_id = #{userId,jdbcType=VARCHAR},",
			"repo_name = #{repoName,jdbcType=VARCHAR},", "deliver_describe = #{deliverDescribe,jdbcType=VARCHAR},",
			"ability_instance = #{abilityInstance,jdbcType=VARCHAR},",
			"resource_type = #{resourceType,jdbcType=INTEGER},", "username = #{username,jdbcType=VARCHAR},",
			"password = #{password,jdbcType=VARCHAR},", "ability_instance_url = #{abilityInstanceUrl,jdbcType=VARCHAR}",
			"where user_ability_instance_id = #{userAbilityInstanceId,jdbcType=INTEGER}" })
	int updateByPrimaryKey(UserAbilityInstanceDetail record);
}