package org.ku8eye.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.ku8eye.domain.UserGroup;

public interface UserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_group",
        "where group_id = #{groupId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_group (group_id, group_name, ",
        "tenant_id, ku8_parttion_ids)",
        "values (#{groupId,jdbcType=INTEGER}, #{groupName,jdbcType=VARCHAR}, ",
        "#{tenantId,jdbcType=INTEGER}, #{ku8ParttionIds,jdbcType=VARCHAR})"
    })
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "group_id, group_name, tenant_id, ku8_parttion_ids",
        "from user_group",
        "where group_id = #{groupId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="group_id", property="groupId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ku8_parttion_ids", property="ku8ParttionIds", jdbcType=JdbcType.VARCHAR)
    })
    UserGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "group_id, group_name, tenant_id, ku8_parttion_ids",
        "from user_group"
    })
    @Results({
        @Result(column="group_id", property="groupId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.INTEGER),
        @Result(column="ku8_parttion_ids", property="ku8ParttionIds", jdbcType=JdbcType.VARCHAR)
    })
    List<UserGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated
     */
    @Update({
        "update user_group",
        "set group_name = #{groupName,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=INTEGER},",
          "ku8_parttion_ids = #{ku8ParttionIds,jdbcType=VARCHAR}",
        "where group_id = #{groupId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserGroup record);
}