package com.iiot.domain;

import java.util.Date;

public class IiotAppList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.app_id
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.app_name
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String appName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.node
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String node;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.status
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.restart_times
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String restartTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.up_time
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String upTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.template
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String template;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.owner
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String owner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.note
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.rest3
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String rest3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.rest4
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String rest4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.rest5
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String rest5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.create_time
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iiot_app_list.uuid
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	private String uuid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.app_id
	 * @return  the value of iiot_app_list.app_id
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.app_id
	 * @param appId  the value for iiot_app_list.app_id
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.app_name
	 * @return  the value of iiot_app_list.app_name
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.app_name
	 * @param appName  the value for iiot_app_list.app_name
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setAppName(String appName) {
		this.appName = appName == null ? null : appName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.node
	 * @return  the value of iiot_app_list.node
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getNode() {
		return node;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.node
	 * @param node  the value for iiot_app_list.node
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setNode(String node) {
		this.node = node == null ? null : node.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.status
	 * @return  the value of iiot_app_list.status
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.status
	 * @param status  the value for iiot_app_list.status
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.restart_times
	 * @return  the value of iiot_app_list.restart_times
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getRestartTimes() {
		return restartTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.restart_times
	 * @param restartTimes  the value for iiot_app_list.restart_times
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setRestartTimes(String restartTimes) {
		this.restartTimes = restartTimes == null ? null : restartTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.up_time
	 * @return  the value of iiot_app_list.up_time
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getUpTime() {
		return upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.up_time
	 * @param upTime  the value for iiot_app_list.up_time
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setUpTime(String upTime) {
		this.upTime = upTime == null ? null : upTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.template
	 * @return  the value of iiot_app_list.template
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getTemplate() {
		return template;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.template
	 * @param template  the value for iiot_app_list.template
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setTemplate(String template) {
		this.template = template == null ? null : template.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.owner
	 * @return  the value of iiot_app_list.owner
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.owner
	 * @param owner  the value for iiot_app_list.owner
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setOwner(String owner) {
		this.owner = owner == null ? null : owner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.note
	 * @return  the value of iiot_app_list.note
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.note
	 * @param note  the value for iiot_app_list.note
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.rest3
	 * @return  the value of iiot_app_list.rest3
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getRest3() {
		return rest3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.rest3
	 * @param rest3  the value for iiot_app_list.rest3
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setRest3(String rest3) {
		this.rest3 = rest3 == null ? null : rest3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.rest4
	 * @return  the value of iiot_app_list.rest4
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getRest4() {
		return rest4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.rest4
	 * @param rest4  the value for iiot_app_list.rest4
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setRest4(String rest4) {
		this.rest4 = rest4 == null ? null : rest4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.rest5
	 * @return  the value of iiot_app_list.rest5
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getRest5() {
		return rest5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.rest5
	 * @param rest5  the value for iiot_app_list.rest5
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setRest5(String rest5) {
		this.rest5 = rest5 == null ? null : rest5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.create_time
	 * @return  the value of iiot_app_list.create_time
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.create_time
	 * @param createTime  the value for iiot_app_list.create_time
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iiot_app_list.uuid
	 * @return  the value of iiot_app_list.uuid
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iiot_app_list.uuid
	 * @param uuid  the value for iiot_app_list.uuid
	 * @mbg.generated  Fri Aug 23 12:05:30 CST 2019
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid == null ? null : uuid.trim();
	}
}