package com.iiot.domain;

import java.util.Date;

public class IiotDeviceInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.ID
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.DEVICE_ENCODE
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String deviceEncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.DEVICE_NAME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.TOPIC_NANME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String topicNanme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.DEVICE_STATUS_CODE
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String deviceStatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.NODE_IP
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String nodeIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.HOSTNAME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String hostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.DESCRIPTION
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.CREATER
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.CREATE_TIME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.MODIFIER
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.MODIFIER_TIME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private Date modifierTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.TIMESTAMP
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.VNO
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private Integer vno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_device_info.REMARK
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.ID
     *
     * @return the value of iiot_device_info.ID
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.ID
     *
     * @param id the value for iiot_device_info.ID
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.DEVICE_ENCODE
     *
     * @return the value of iiot_device_info.DEVICE_ENCODE
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getDeviceEncode() {
        return deviceEncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.DEVICE_ENCODE
     *
     * @param deviceEncode the value for iiot_device_info.DEVICE_ENCODE
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setDeviceEncode(String deviceEncode) {
        this.deviceEncode = deviceEncode == null ? null : deviceEncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.DEVICE_NAME
     *
     * @return the value of iiot_device_info.DEVICE_NAME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.DEVICE_NAME
     *
     * @param deviceName the value for iiot_device_info.DEVICE_NAME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.TOPIC_NANME
     *
     * @return the value of iiot_device_info.TOPIC_NANME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getTopicNanme() {
        return topicNanme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.TOPIC_NANME
     *
     * @param topicNanme the value for iiot_device_info.TOPIC_NANME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setTopicNanme(String topicNanme) {
        this.topicNanme = topicNanme == null ? null : topicNanme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.DEVICE_STATUS_CODE
     *
     * @return the value of iiot_device_info.DEVICE_STATUS_CODE
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getDeviceStatusCode() {
        return deviceStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.DEVICE_STATUS_CODE
     *
     * @param deviceStatusCode the value for iiot_device_info.DEVICE_STATUS_CODE
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setDeviceStatusCode(String deviceStatusCode) {
        this.deviceStatusCode = deviceStatusCode == null ? null : deviceStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.NODE_IP
     *
     * @return the value of iiot_device_info.NODE_IP
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getNodeIp() {
        return nodeIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.NODE_IP
     *
     * @param nodeIp the value for iiot_device_info.NODE_IP
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setNodeIp(String nodeIp) {
        this.nodeIp = nodeIp == null ? null : nodeIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.HOSTNAME
     *
     * @return the value of iiot_device_info.HOSTNAME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.HOSTNAME
     *
     * @param hostname the value for iiot_device_info.HOSTNAME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.DESCRIPTION
     *
     * @return the value of iiot_device_info.DESCRIPTION
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.DESCRIPTION
     *
     * @param description the value for iiot_device_info.DESCRIPTION
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.CREATER
     *
     * @return the value of iiot_device_info.CREATER
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.CREATER
     *
     * @param creater the value for iiot_device_info.CREATER
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.CREATE_TIME
     *
     * @return the value of iiot_device_info.CREATE_TIME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.CREATE_TIME
     *
     * @param createTime the value for iiot_device_info.CREATE_TIME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.MODIFIER
     *
     * @return the value of iiot_device_info.MODIFIER
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.MODIFIER
     *
     * @param modifier the value for iiot_device_info.MODIFIER
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.MODIFIER_TIME
     *
     * @return the value of iiot_device_info.MODIFIER_TIME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.MODIFIER_TIME
     *
     * @param modifierTime the value for iiot_device_info.MODIFIER_TIME
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.TIMESTAMP
     *
     * @return the value of iiot_device_info.TIMESTAMP
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.TIMESTAMP
     *
     * @param timestamp the value for iiot_device_info.TIMESTAMP
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.VNO
     *
     * @return the value of iiot_device_info.VNO
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public Integer getVno() {
        return vno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.VNO
     *
     * @param vno the value for iiot_device_info.VNO
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setVno(Integer vno) {
        this.vno = vno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_device_info.REMARK
     *
     * @return the value of iiot_device_info.REMARK
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_device_info.REMARK
     *
     * @param remark the value for iiot_device_info.REMARK
     *
     * @mbg.generated Fri Aug 09 11:46:57 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}