package com.iiot.domain;

import java.util.Date;

public class IiotProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.TENANT_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.OWNER
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.NAME
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.ICON_URL
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.VERSION
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.RES_PART
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String resPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.APP_TYPE
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Byte appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.ZONE_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Integer zoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.CLUSTER_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Integer clusterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.RES_PARTION_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Integer resPartionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.STATUS
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.PROGRESS
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Integer progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.NOTE
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.LAST_UPDATED
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private Date lastUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.PROJECT_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.JSON_SPEC
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String jsonSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iiot_project.PREV_JSON_SPEC
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    private String prevJsonSpec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.ID
     *
     * @return the value of iiot_project.ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.ID
     *
     * @param id the value for iiot_project.ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.TENANT_ID
     *
     * @return the value of iiot_project.TENANT_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.TENANT_ID
     *
     * @param tenantId the value for iiot_project.TENANT_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.OWNER
     *
     * @return the value of iiot_project.OWNER
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.OWNER
     *
     * @param owner the value for iiot_project.OWNER
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.NAME
     *
     * @return the value of iiot_project.NAME
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.NAME
     *
     * @param name the value for iiot_project.NAME
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.ICON_URL
     *
     * @return the value of iiot_project.ICON_URL
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.ICON_URL
     *
     * @param iconUrl the value for iiot_project.ICON_URL
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.VERSION
     *
     * @return the value of iiot_project.VERSION
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.VERSION
     *
     * @param version the value for iiot_project.VERSION
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.RES_PART
     *
     * @return the value of iiot_project.RES_PART
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getResPart() {
        return resPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.RES_PART
     *
     * @param resPart the value for iiot_project.RES_PART
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setResPart(String resPart) {
        this.resPart = resPart == null ? null : resPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.APP_TYPE
     *
     * @return the value of iiot_project.APP_TYPE
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Byte getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.APP_TYPE
     *
     * @param appType the value for iiot_project.APP_TYPE
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setAppType(Byte appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.ZONE_ID
     *
     * @return the value of iiot_project.ZONE_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.ZONE_ID
     *
     * @param zoneId the value for iiot_project.ZONE_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.CLUSTER_ID
     *
     * @return the value of iiot_project.CLUSTER_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.CLUSTER_ID
     *
     * @param clusterId the value for iiot_project.CLUSTER_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.RES_PARTION_ID
     *
     * @return the value of iiot_project.RES_PARTION_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Integer getResPartionId() {
        return resPartionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.RES_PARTION_ID
     *
     * @param resPartionId the value for iiot_project.RES_PARTION_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setResPartionId(Integer resPartionId) {
        this.resPartionId = resPartionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.STATUS
     *
     * @return the value of iiot_project.STATUS
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.STATUS
     *
     * @param status the value for iiot_project.STATUS
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.PROGRESS
     *
     * @return the value of iiot_project.PROGRESS
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.PROGRESS
     *
     * @param progress the value for iiot_project.PROGRESS
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.NOTE
     *
     * @return the value of iiot_project.NOTE
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.NOTE
     *
     * @param note the value for iiot_project.NOTE
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.LAST_UPDATED
     *
     * @return the value of iiot_project.LAST_UPDATED
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.LAST_UPDATED
     *
     * @param lastUpdated the value for iiot_project.LAST_UPDATED
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.PROJECT_ID
     *
     * @return the value of iiot_project.PROJECT_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.PROJECT_ID
     *
     * @param projectId the value for iiot_project.PROJECT_ID
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.JSON_SPEC
     *
     * @return the value of iiot_project.JSON_SPEC
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getJsonSpec() {
        return jsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.JSON_SPEC
     *
     * @param jsonSpec the value for iiot_project.JSON_SPEC
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setJsonSpec(String jsonSpec) {
        this.jsonSpec = jsonSpec == null ? null : jsonSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iiot_project.PREV_JSON_SPEC
     *
     * @return the value of iiot_project.PREV_JSON_SPEC
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public String getPrevJsonSpec() {
        return prevJsonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iiot_project.PREV_JSON_SPEC
     *
     * @param prevJsonSpec the value for iiot_project.PREV_JSON_SPEC
     *
     * @mbg.generated Thu Jul 18 14:46:21 CST 2019
     */
    public void setPrevJsonSpec(String prevJsonSpec) {
        this.prevJsonSpec = prevJsonSpec == null ? null : prevJsonSpec.trim();
    }
}