package com.iiot.dao;

import com.iiot.domain.IiotAppList;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface IiotAppListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iiot_app_list
	 * @mbg.generated  Fri Jul 26 10:32:18 CST 2019
	 */
	@Delete({ "delete from iiot_app_list", "where app_id = #{appId,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer appId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iiot_app_list
	 * @mbg.generated  Fri Jul 26 10:32:18 CST 2019
	 */
	@Insert({ "insert into iiot_app_list (app_id, app_name, ", "node, status, restart_times, ", "up_time, template, ",
			"owner, note, rest3, ", "rest4, rest5, create_time, ", "uuid)",
			"values (#{appId,jdbcType=INTEGER}, #{appName,jdbcType=VARCHAR}, ",
			"#{node,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, #{restartTimes,jdbcType=CHAR}, ",
			"#{upTime,jdbcType=VARCHAR}, #{template,jdbcType=VARCHAR}, ",
			"#{owner,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR}, #{rest3,jdbcType=VARCHAR}, ",
			"#{rest4,jdbcType=VARCHAR}, #{rest5,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
			"#{uuid,jdbcType=CHAR})" })
	int insert(IiotAppList record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iiot_app_list
	 * @mbg.generated  Fri Jul 26 10:32:18 CST 2019
	 */
	@Insert({ "insert into iiot_app_list (app_id, app_name, ", "node, status, restart_times, ", "up_time, template, ",
			"owner, note, rest3, ", "rest4, rest5, create_time, ", "uuid)",
			"values (#{appId,jdbcType=INTEGER}, #{appName,jdbcType=VARCHAR}, ",
			"#{node,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, #{restartTimes,jdbcType=CHAR}, ",
			"#{upTime,jdbcType=VARCHAR}, #{template,jdbcType=VARCHAR}, ",
			"#{owner,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR}, #{rest3,jdbcType=VARCHAR}, ",
			"#{rest4,jdbcType=VARCHAR}, #{rest5,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
			"#{uuid,jdbcType=CHAR})" })
	@Options(useGeneratedKeys = true, keyProperty = "appId",keyColumn="app_id" )
	int insertAndGetId(IiotAppList record);
	
	
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iiot_app_list
	 * @mbg.generated  Fri Jul 26 10:32:18 CST 2019
	 */
	@Select({ "select", "app_id, app_name, node, status, restart_times, up_time, template, owner, note, ",
			"rest3, rest4, rest5, create_time, uuid", "from iiot_app_list",
			"where app_id = #{appId,jdbcType=INTEGER}" })
	@Results({ @Result(column = "app_id", property = "appId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "app_name", property = "appName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "node", property = "node", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
			@Result(column = "restart_times", property = "restartTimes", jdbcType = JdbcType.CHAR),
			@Result(column = "up_time", property = "upTime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "template", property = "template", jdbcType = JdbcType.VARCHAR),
			@Result(column = "owner", property = "owner", jdbcType = JdbcType.VARCHAR),
			@Result(column = "note", property = "note", jdbcType = JdbcType.VARCHAR),
			@Result(column = "rest3", property = "rest3", jdbcType = JdbcType.VARCHAR),
			@Result(column = "rest4", property = "rest4", jdbcType = JdbcType.VARCHAR),
			@Result(column = "rest5", property = "rest5", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "uuid", property = "uuid", jdbcType = JdbcType.CHAR) })
	IiotAppList selectByPrimaryKey(Integer appId);
	
	@Select({ "select", "app_id, app_name, node, status, restart_times, up_time, template, owner, note, ",
		"rest3, rest4, rest5, create_time, uuid", "from iiot_app_list",
		"where owner = #{owner,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "app_id", property = "appId", jdbcType = JdbcType.INTEGER, id = true),
		@Result(column = "app_name", property = "appName", jdbcType = JdbcType.VARCHAR),
		@Result(column = "node", property = "node", jdbcType = JdbcType.VARCHAR),
		@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
		@Result(column = "restart_times", property = "restartTimes", jdbcType = JdbcType.CHAR),
		@Result(column = "up_time", property = "upTime", jdbcType = JdbcType.VARCHAR),
		@Result(column = "template", property = "template", jdbcType = JdbcType.VARCHAR),
		@Result(column = "owner", property = "owner", jdbcType = JdbcType.VARCHAR),
		@Result(column = "note", property = "note", jdbcType = JdbcType.VARCHAR),
		@Result(column = "rest3", property = "rest3", jdbcType = JdbcType.VARCHAR),
		@Result(column = "rest4", property = "rest4", jdbcType = JdbcType.VARCHAR),
		@Result(column = "rest5", property = "rest5", jdbcType = JdbcType.VARCHAR),
		@Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
		@Result(column = "uuid", property = "uuid", jdbcType = JdbcType.CHAR) })
	List<IiotAppList> selectByOwner(String owner);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iiot_app_list
	 * @mbg.generated  Fri Jul 26 10:32:18 CST 2019
	 */
	@Select({ "select", "app_id, app_name, node, status, restart_times, up_time, template, owner, note, ",
			"rest3, rest4, rest5, create_time, uuid", "from iiot_app_list" })
	@Results({ @Result(column = "app_id", property = "appId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "app_name", property = "appName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "node", property = "node", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
			@Result(column = "restart_times", property = "restartTimes", jdbcType = JdbcType.CHAR),
			@Result(column = "up_time", property = "upTime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "template", property = "template", jdbcType = JdbcType.VARCHAR),
			@Result(column = "owner", property = "owner", jdbcType = JdbcType.VARCHAR),
			@Result(column = "note", property = "note", jdbcType = JdbcType.VARCHAR),
			@Result(column = "rest3", property = "rest3", jdbcType = JdbcType.VARCHAR),
			@Result(column = "rest4", property = "rest4", jdbcType = JdbcType.VARCHAR),
			@Result(column = "rest5", property = "rest5", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "uuid", property = "uuid", jdbcType = JdbcType.CHAR) })
	List<IiotAppList> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iiot_app_list
	 * @mbg.generated  Fri Jul 26 10:32:18 CST 2019
	 */
	@Update({ "update iiot_app_list", "set app_name = #{appName,jdbcType=VARCHAR},", "node = #{node,jdbcType=VARCHAR},",
			"status = #{status,jdbcType=INTEGER},", "restart_times = #{restartTimes,jdbcType=CHAR},",
			"up_time = #{upTime,jdbcType=VARCHAR},", "template = #{template,jdbcType=VARCHAR},",
			"owner = #{owner,jdbcType=VARCHAR},", "note = #{note,jdbcType=VARCHAR},",
			"rest3 = #{rest3,jdbcType=VARCHAR},", "rest4 = #{rest4,jdbcType=VARCHAR},",
			"rest5 = #{rest5,jdbcType=VARCHAR},", "create_time = #{createTime,jdbcType=TIMESTAMP},",
			"uuid = #{uuid,jdbcType=CHAR}", "where app_id = #{appId,jdbcType=INTEGER}" })
	int updateByPrimaryKey(IiotAppList record);
	
	/**
     * 
     * 
     * @Title: insertSysRole2
     * 
     * @Description: insertSysRole2 返回自增主键的情况
     * 
     * @param sysRole
     * @return
     * 
     * @return: int
     
    @Insert({ "insert into sys_role(role_name, enabled, create_by, create_time) values(#{roleName}, #{enabled}, #{createBy}, #{createTime, jdbcType=TIMESTAMP})" })
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insertSysRole2(SysRole sysRole);
*/

}